// <auto-generated />
using System;
using BooksMagazine.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BooksMagazine.Migrations
{
    [DbContext(typeof(BooksMagazineContext))]
    [Migration("20200720115236_HomeMigration")]
    partial class HomeMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BooksMagazine.Models.HomeModels.CarouselItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("HomeId")
                        .HasColumnType("int");

                    b.Property<string>("ImageLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Quote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HomeId");

                    b.ToTable("CarouselItem");
                });

            modelBuilder.Entity("BooksMagazine.Models.HomeModels.Home", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("WelcomeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WelcomeId");

                    b.ToTable("Home");
                });

            modelBuilder.Entity("BooksMagazine.Models.HomeModels.Purpose", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("WelcomeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WelcomeId");

                    b.ToTable("Purpose");
                });

            modelBuilder.Entity("BooksMagazine.Models.HomeModels.Topic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("HomeId")
                        .HasColumnType("int");

                    b.Property<string>("ImageLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HomeId");

                    b.ToTable("Topic");
                });

            modelBuilder.Entity("BooksMagazine.Models.HomeModels.Welcome", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GoalTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Welcome");
                });

            modelBuilder.Entity("BooksMagazine.Models.HomeModels.CarouselItem", b =>
                {
                    b.HasOne("BooksMagazine.Models.HomeModels.Home", null)
                        .WithMany("CarouselItems")
                        .HasForeignKey("HomeId");
                });

            modelBuilder.Entity("BooksMagazine.Models.HomeModels.Home", b =>
                {
                    b.HasOne("BooksMagazine.Models.HomeModels.Welcome", "Welcome")
                        .WithMany()
                        .HasForeignKey("WelcomeId");
                });

            modelBuilder.Entity("BooksMagazine.Models.HomeModels.Purpose", b =>
                {
                    b.HasOne("BooksMagazine.Models.HomeModels.Welcome", null)
                        .WithMany("Purposes")
                        .HasForeignKey("WelcomeId");
                });

            modelBuilder.Entity("BooksMagazine.Models.HomeModels.Topic", b =>
                {
                    b.HasOne("BooksMagazine.Models.HomeModels.Home", null)
                        .WithMany("Topics")
                        .HasForeignKey("HomeId");
                });
#pragma warning restore 612, 618
        }
    }
}
